
services:
  brainstorm:
    image: brainstorm-app:0.0.1
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: brainstorm-app
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
      - /var/log/nginx
